datafile = "/mnt/d/work/experiment/OnlineDataAnalysisSystem/2026_209Bi_Exp/Analysis/puyuan82_data/204Pt78/sum_204Pt78_weak_signals.root"
filep = "/mnt/d/work/experiment/OnlineDataAnalysisSystem/2026_209Bi_Exp/Analysis/exercise_209Bi31_204Pt78_2026/204Pt78Setting_1.5/3.2026_209Bi31_204Pt78_Al_1.50.lpp"
remove_baseline_checkbox = false
psd_baseline_removed_l = "10000"
psd_baseline_removed_ratio = "1e-9"
alphap = "1.421"
alphap_min = "1.35"
alphap_max = "1.5"
alphap_step = "0.001"
threshold = "100"
matching_freq_min = "307000000"
matching_freq_max = "311000000"
peak_threshold_pct = 5.0
min_distance = 500.0
fref_min = "308559917.77"
fref_max = "310027543.56"
harmonics = "385 386 387 388"
refion = "204Pt78+"
highlight_ions = "209Bi80+"
circumference = "277.2929"
mode = "Bρ"
value = "9.057533"
sim_scalingfactor = "5e-2"
reload_data = false
nions = "10000"
simulation_result = "/mnt/d/work/experiment/OnlineDataAnalysisSystem/2026_209Bi_Exp/Analysis/exercise_209Bi31_204Pt78_2026/simulation_result.out"
matched_result = "/mnt/d/work/experiment/OnlineDataAnalysisSystem/2026_209Bi_Exp/Analysis/exercise_209Bi31_204Pt78_2026/best_match_details.csv"
